# Copyright (c) Microsoft Corporation.
# Licensed under the MIT license.

[tool.pytest.ini_options]
filterwarnings = ["ignore::DeprecationWarning:torchvision.*", "ignore::DeprecationWarning:pyreadline.*"]
