name: Run Unitary Tests

on:
  push:

jobs:
  test-pytest:
    name: Tests with PyTest
    runs-on: ubuntu-latest
    steps:
      - name: Pulls the repository
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Sets the environment
        uses: actions/setup-python@v1
        with:
          python-version: 3.7
      - name: Installs requirements
        shell: bash -l {0}
        run: |
          python -m pip install --user -e .
      - name: Runs the tests
        shell: bash -l {0}
        run: |
          python -m pytest tests
